/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author MINEDUCYT
 */
public class Acordes extends javax.swing.JFrame {

    /**
     * Creates new form Acordes
     */
    public Acordes() {
        initComponents();

        setSize(730, 535);
        setResizable(false);
        setTitle(" Galeria de Acordes");
        this.setLocationRelativeTo(null);
         
        ImageIcon wallpaper = new ImageIcon("src/img/wallpaperPiano.jpg");
        Icon icon = new ImageIcon(wallpaper.getImage().getScaledInstance(LabelWallpaper.getWidth(),
                LabelWallpaper.getHeight(), Image.SCALE_DEFAULT));

        LabelWallpaper.setIcon(icon);

    }
    
@Override
public Image getIconImage() {
    URL resourceUrl = ClassLoader.getSystemResource("img/icono.png");
    if (resourceUrl != null) {
        Image retValue = Toolkit.getDefaultToolkit().getImage(resourceUrl);
        return retValue;
    } else {
        System.err.println("No se pudo encontrar el recurso 'icono.png'");
        return null;
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CmbAcorde = new javax.swing.JComboBox<>();
        CmbFamilia = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        LabelAcorde = new javax.swing.JLabel();
        LabelAcordeName = new javax.swing.JLabel();
        DOSos3 = new javax.swing.JButton();
        RESos3 = new javax.swing.JButton();
        FASos3 = new javax.swing.JButton();
        SOLSos3 = new javax.swing.JButton();
        LASos3 = new javax.swing.JButton();
        DO3 = new javax.swing.JButton();
        RE3 = new javax.swing.JButton();
        MI3 = new javax.swing.JButton();
        FA3 = new javax.swing.JButton();
        SOL3 = new javax.swing.JButton();
        LA3 = new javax.swing.JButton();
        SI3 = new javax.swing.JButton();
        DOSos2 = new javax.swing.JButton();
        RESos2 = new javax.swing.JButton();
        FASos2 = new javax.swing.JButton();
        SOLSos2 = new javax.swing.JButton();
        LASos2 = new javax.swing.JButton();
        DO2 = new javax.swing.JButton();
        RE2 = new javax.swing.JButton();
        MI2 = new javax.swing.JButton();
        FA2 = new javax.swing.JButton();
        SOL2 = new javax.swing.JButton();
        LA2 = new javax.swing.JButton();
        SI2 = new javax.swing.JButton();
        DOSos1 = new javax.swing.JButton();
        RESos1 = new javax.swing.JButton();
        FASos1 = new javax.swing.JButton();
        LASos1 = new javax.swing.JButton();
        SOLSos1 = new javax.swing.JButton();
        MI1 = new javax.swing.JButton();
        FA1 = new javax.swing.JButton();
        RE1 = new javax.swing.JButton();
        DO1 = new javax.swing.JButton();
        SOL1 = new javax.swing.JButton();
        LA1 = new javax.swing.JButton();
        SI1 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        LabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CmbAcorde.setBackground(new java.awt.Color(51, 51, 51));
        CmbAcorde.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        CmbAcorde.setForeground(new java.awt.Color(255, 255, 255));
        CmbAcorde.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DO", "DO#", "RE", "RE#", "MI", "FA", "FA#", "SOL", "SOL#", "LA", "LA#", "SI" }));
        getContentPane().add(CmbAcorde, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 207, 40));

        CmbFamilia.setBackground(new java.awt.Color(51, 51, 51));
        CmbFamilia.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        CmbFamilia.setForeground(new java.awt.Color(255, 255, 255));
        CmbFamilia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mayor", "Menor", "Quinta", "Sus2", "Sus4", "Aumentado", "Disminuido", "Séptima", "Octava", "Novena", "Maj6", "Maj7", "Maj9", "Maj11", "Maj13" }));
        getContentPane().add(CmbFamilia, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 40, 212, 40));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("C=DO   D=RE   E=MI   F=FA   G=SOL   A=LA   B=SI   #=SOSTENIDO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 530, 29));

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Acorde");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 11, -1, 30));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Familia");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 70, 30));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Generar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 41, 119, 40));

        LabelAcorde.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        LabelAcorde.setForeground(new java.awt.Color(255, 255, 255));
        LabelAcorde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelAcorde.setText("ACORDE");
        getContentPane().add(LabelAcorde, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 418, 430, -1));

        LabelAcordeName.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        LabelAcordeName.setForeground(new java.awt.Color(255, 255, 255));
        LabelAcordeName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelAcordeName.setText("Nombre del acorde");
        getContentPane().add(LabelAcordeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 476, 430, -1));

        DOSos3.setBackground(new java.awt.Color(0, 0, 0));
        DOSos3.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        DOSos3.setForeground(new java.awt.Color(255, 255, 255));
        DOSos3.setText("C#");
        DOSos3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(DOSos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 20, 80));

        RESos3.setBackground(new java.awt.Color(0, 0, 0));
        RESos3.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        RESos3.setForeground(new java.awt.Color(255, 255, 255));
        RESos3.setText("D#");
        RESos3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(RESos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 20, 80));

        FASos3.setBackground(new java.awt.Color(0, 0, 0));
        FASos3.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        FASos3.setForeground(new java.awt.Color(255, 255, 255));
        FASos3.setText("F#");
        FASos3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(FASos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 20, 80));

        SOLSos3.setBackground(new java.awt.Color(0, 0, 0));
        SOLSos3.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        SOLSos3.setForeground(new java.awt.Color(255, 255, 255));
        SOLSos3.setText("G#");
        SOLSos3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(SOLSos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 20, 80));

        LASos3.setBackground(new java.awt.Color(0, 0, 0));
        LASos3.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        LASos3.setForeground(new java.awt.Color(255, 255, 255));
        LASos3.setText("A#");
        LASos3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(LASos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 20, 80));

        DO3.setBackground(new java.awt.Color(255, 255, 255));
        DO3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        DO3.setForeground(new java.awt.Color(0, 0, 0));
        DO3.setText("C");
        DO3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(DO3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 30, 130));

        RE3.setBackground(new java.awt.Color(255, 255, 255));
        RE3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        RE3.setForeground(new java.awt.Color(0, 0, 0));
        RE3.setText("D");
        RE3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(RE3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 30, 130));

        MI3.setBackground(new java.awt.Color(255, 255, 255));
        MI3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        MI3.setForeground(new java.awt.Color(0, 0, 0));
        MI3.setText("E");
        MI3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(MI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 30, 130));

        FA3.setBackground(new java.awt.Color(255, 255, 255));
        FA3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        FA3.setForeground(new java.awt.Color(0, 0, 0));
        FA3.setText("F");
        FA3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(FA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 30, 130));

        SOL3.setBackground(new java.awt.Color(255, 255, 255));
        SOL3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        SOL3.setForeground(new java.awt.Color(0, 0, 0));
        SOL3.setText("G");
        SOL3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(SOL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 30, 130));

        LA3.setBackground(new java.awt.Color(255, 255, 255));
        LA3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        LA3.setForeground(new java.awt.Color(0, 0, 0));
        LA3.setText("A");
        LA3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(LA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 30, 130));

        SI3.setBackground(new java.awt.Color(255, 255, 255));
        SI3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        SI3.setForeground(new java.awt.Color(0, 0, 0));
        SI3.setText("B");
        SI3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(SI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 30, 130));

        DOSos2.setBackground(new java.awt.Color(0, 0, 0));
        DOSos2.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        DOSos2.setForeground(new java.awt.Color(255, 255, 255));
        DOSos2.setText("C#");
        DOSos2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(DOSos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 20, 80));

        RESos2.setBackground(new java.awt.Color(0, 0, 0));
        RESos2.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        RESos2.setForeground(new java.awt.Color(255, 255, 255));
        RESos2.setText("D#");
        RESos2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(RESos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 20, 80));

        FASos2.setBackground(new java.awt.Color(0, 0, 0));
        FASos2.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        FASos2.setForeground(new java.awt.Color(255, 255, 255));
        FASos2.setText("F#");
        FASos2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(FASos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 20, 80));

        SOLSos2.setBackground(new java.awt.Color(0, 0, 0));
        SOLSos2.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        SOLSos2.setForeground(new java.awt.Color(255, 255, 255));
        SOLSos2.setText("G#");
        SOLSos2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(SOLSos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 20, 80));

        LASos2.setBackground(new java.awt.Color(0, 0, 0));
        LASos2.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        LASos2.setForeground(new java.awt.Color(255, 255, 255));
        LASos2.setText("A#");
        LASos2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(LASos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 20, 80));

        DO2.setBackground(new java.awt.Color(255, 255, 255));
        DO2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        DO2.setForeground(new java.awt.Color(0, 0, 0));
        DO2.setText("C");
        DO2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(DO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 30, 130));

        RE2.setBackground(new java.awt.Color(255, 255, 255));
        RE2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        RE2.setForeground(new java.awt.Color(0, 0, 0));
        RE2.setText("D");
        RE2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(RE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 30, 130));

        MI2.setBackground(new java.awt.Color(255, 255, 255));
        MI2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        MI2.setForeground(new java.awt.Color(0, 0, 0));
        MI2.setText("E");
        MI2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(MI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 30, 130));

        FA2.setBackground(new java.awt.Color(255, 255, 255));
        FA2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        FA2.setForeground(new java.awt.Color(0, 0, 0));
        FA2.setText("F");
        FA2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(FA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 30, 130));

        SOL2.setBackground(new java.awt.Color(255, 255, 255));
        SOL2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        SOL2.setForeground(new java.awt.Color(0, 0, 0));
        SOL2.setText("G");
        SOL2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(SOL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 30, 130));

        LA2.setBackground(new java.awt.Color(255, 255, 255));
        LA2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        LA2.setForeground(new java.awt.Color(0, 0, 0));
        LA2.setText("A");
        LA2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(LA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 30, 130));

        SI2.setBackground(new java.awt.Color(255, 255, 255));
        SI2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        SI2.setForeground(new java.awt.Color(0, 0, 0));
        SI2.setText("B");
        SI2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(SI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 30, 130));

        DOSos1.setBackground(new java.awt.Color(0, 0, 0));
        DOSos1.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        DOSos1.setForeground(new java.awt.Color(255, 255, 255));
        DOSos1.setText("C#");
        DOSos1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(DOSos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 20, 80));

        RESos1.setBackground(new java.awt.Color(0, 0, 0));
        RESos1.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        RESos1.setForeground(new java.awt.Color(255, 255, 255));
        RESos1.setText("D#");
        RESos1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(RESos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 20, 80));

        FASos1.setBackground(new java.awt.Color(0, 0, 0));
        FASos1.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        FASos1.setForeground(new java.awt.Color(255, 255, 255));
        FASos1.setText("F#");
        FASos1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(FASos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 20, 80));

        LASos1.setBackground(new java.awt.Color(0, 0, 0));
        LASos1.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        LASos1.setForeground(new java.awt.Color(255, 255, 255));
        LASos1.setText("A#");
        LASos1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(LASos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 20, 80));

        SOLSos1.setBackground(new java.awt.Color(0, 0, 0));
        SOLSos1.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        SOLSos1.setForeground(new java.awt.Color(255, 255, 255));
        SOLSos1.setText("G#");
        SOLSos1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(SOLSos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 20, 80));

        MI1.setBackground(new java.awt.Color(255, 255, 255));
        MI1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        MI1.setForeground(new java.awt.Color(0, 0, 0));
        MI1.setText("E");
        MI1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(MI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 30, 130));

        FA1.setBackground(new java.awt.Color(255, 255, 255));
        FA1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        FA1.setForeground(new java.awt.Color(0, 0, 0));
        FA1.setText("F");
        FA1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(FA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 30, 130));

        RE1.setBackground(new java.awt.Color(255, 255, 255));
        RE1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        RE1.setForeground(new java.awt.Color(0, 0, 0));
        RE1.setText("D");
        RE1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(RE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 30, 130));

        DO1.setBackground(new java.awt.Color(255, 255, 255));
        DO1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        DO1.setForeground(new java.awt.Color(0, 0, 0));
        DO1.setText("C");
        DO1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(DO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 30, 130));

        SOL1.setBackground(new java.awt.Color(255, 255, 255));
        SOL1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        SOL1.setForeground(new java.awt.Color(0, 0, 0));
        SOL1.setText("G");
        SOL1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(SOL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 30, 130));

        LA1.setBackground(new java.awt.Color(255, 255, 255));
        LA1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        LA1.setForeground(new java.awt.Color(0, 0, 0));
        LA1.setText("A");
        LA1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(LA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 30, 130));

        SI1.setBackground(new java.awt.Color(255, 255, 255));
        SI1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        SI1.setForeground(new java.awt.Color(0, 0, 0));
        SI1.setText("B");
        SI1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(SI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 30, 130));

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 450, 90));

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 80, 30));
        jTextField8.getAccessibleContext().setAccessibleName("");

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 80, 30));

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 530, 30));
        getContentPane().add(LabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

 int Acorde = CmbAcorde.getSelectedIndex();
        int Familia = CmbFamilia.getSelectedIndex();
        Color ColorTecla = Color.BLUE;

        //Naturales
        if (Familia == 0) {
            if (Acorde == 0) {

                Limpiar();
                DO1.setBackground(ColorTecla);
                MI1.setBackground(ColorTecla);
                SOL1.setBackground(ColorTecla);
                LabelAcorde.setText("C");
                LabelAcordeName.setText("Do Mayor");
            }
            if (Acorde == 1) {
                Limpiar();
                DOSos1.setBackground(ColorTecla);
                FA1.setBackground(ColorTecla);
                SOLSos1.setBackground(ColorTecla);
                LabelAcorde.setText("C#");
                LabelAcordeName.setText("Do Sostenido Mayor");
            }
            if (Acorde == 2) {
                Limpiar();
                RE1.setBackground(ColorTecla);
                FASos1.setBackground(ColorTecla);
                LA1.setBackground(ColorTecla);
                LabelAcorde.setText("D");
                LabelAcordeName.setText("RE Mayor");
            }
            if (Acorde == 3) {
                Limpiar();
                RESos1.setBackground(ColorTecla);
                SOL1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                LabelAcorde.setText("D#");
                LabelAcordeName.setText("RE Sostenido Mayor");
            }
            if (Acorde == 4) {
                Limpiar();
                MI1.setBackground(ColorTecla);
                SOLSos1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                LabelAcorde.setText("E");
                LabelAcordeName.setText("MI Mayor");
            }
            if (Acorde == 5) {
                Limpiar();
                FA1.setBackground(ColorTecla);
                LA1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                LabelAcorde.setText("F");
                LabelAcordeName.setText("FA Mayor");
            }
            if (Acorde == 6) {
                Limpiar();
                FASos1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                LabelAcorde.setText("F#");
                LabelAcordeName.setText("FA Sostenido Mayor");
            }
            if (Acorde == 7) {
                Limpiar();
                SOL1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                LabelAcorde.setText("G");
                LabelAcordeName.setText("SOL Mayor");
            }
            if (Acorde == 8) {
                Limpiar();
                SOLSos1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                LabelAcorde.setText("G#");
                LabelAcordeName.setText("SOL Sostenido Mayor");
            }
            if (Acorde == 9) {
                Limpiar();
                LA1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                MI2.setBackground(ColorTecla);
                LabelAcorde.setText("A");
                LabelAcordeName.setText("LA Mayor");
            }
            if (Acorde == 10) {
                Limpiar();
                LASos1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                FA2.setBackground(ColorTecla);
                LabelAcorde.setText("A#");
                LabelAcordeName.setText("LA Sostenido Mayor");
            }
            if (Acorde == 11) {
                Limpiar();
                SI1.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                FASos2.setBackground(ColorTecla);
                LabelAcorde.setText("B");
                LabelAcordeName.setText("SI Mayor");
            }
        }

        //Menores
        if (Familia == 1) {
            if (Acorde == 0) {
                Limpiar();
                DO1.setBackground(ColorTecla);
                RESos1.setBackground(ColorTecla);
                SOL1.setBackground(ColorTecla);
                LabelAcorde.setText("Cm");
                LabelAcordeName.setText("Do Menor");
            }
            if (Acorde == 1) {
                Limpiar();
                DOSos1.setBackground(ColorTecla);
                MI1.setBackground(ColorTecla);
                SOLSos1.setBackground(ColorTecla);
                LabelAcorde.setText("C#m");
                LabelAcordeName.setText("Do Sostenido Menor");
            }
            if (Acorde == 2) {
                Limpiar();
                RE1.setBackground(ColorTecla);
                FA1.setBackground(ColorTecla);
                LA1.setBackground(ColorTecla);
                LabelAcorde.setText("Dm");
                LabelAcordeName.setText("RE Menor");
            }
            if (Acorde == 3) {
                Limpiar();
                RESos1.setBackground(ColorTecla);
                FASos1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                LabelAcorde.setText("D#m");
                LabelAcordeName.setText("RE Sostenido Menor");

            }
            if (Acorde == 4) {
                Limpiar();
                MI1.setBackground(ColorTecla);
                SOL1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                LabelAcorde.setText("Em");
                LabelAcordeName.setText("MI Menor");
            }
            if (Acorde == 5) {
                Limpiar();
                FA1.setBackground(ColorTecla);
                SOLSos1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                LabelAcorde.setText("Fm");
                LabelAcordeName.setText("FA menor");
            }
            if (Acorde == 6) {
                Limpiar();
                FASos1.setBackground(ColorTecla);
                LA1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                LabelAcorde.setText("F#m");
                LabelAcordeName.setText("FA Sostenido Menor");
            }
            if (Acorde == 7) {
                Limpiar();
                SOL1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                LabelAcorde.setText("Gm");
                LabelAcordeName.setText("SOL Menor");
            }
            if (Acorde == 8) {
                Limpiar();
                SOLSos1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                LabelAcorde.setText("G#m");
                LabelAcordeName.setText("SOL Sostenido Menor");
            }
            if (Acorde == 9) {
                Limpiar();
                LA1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                MI2.setBackground(ColorTecla);
                LabelAcorde.setText("Am");
                LabelAcordeName.setText("LA Menor");
            }
            if (Acorde == 10) {
                Limpiar();
                LASos1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                FA2.setBackground(ColorTecla);
                LabelAcorde.setText("A#m");
                LabelAcordeName.setText("LA Sostenido Menor");
            }
            if (Acorde == 11) {
                Limpiar();
                SI1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                FASos2.setBackground(ColorTecla);
                LabelAcorde.setText("Bm");
                LabelAcordeName.setText("SI Menor");
            }
        }

        //Quinta
        if (Familia == 2) {
            if (Acorde == 0) {
                Limpiar();
                DO1.setBackground(ColorTecla);
                SOL1.setBackground(ColorTecla);
                LabelAcorde.setText("C5");
                LabelAcordeName.setText("Do Quinta");
            }
            if (Acorde == 1) {
                Limpiar();
                DOSos1.setBackground(ColorTecla);
                SOLSos1.setBackground(ColorTecla);
                LabelAcorde.setText("C#5");
                LabelAcordeName.setText("Do Sostenido Quinta");
            }
            if (Acorde == 2) {
                Limpiar();
                RE1.setBackground(ColorTecla);
                LA1.setBackground(ColorTecla);
                LabelAcorde.setText("D5");
                LabelAcordeName.setText("RE Quinta");
            }
            if (Acorde == 3) {
                Limpiar();
                RESos1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                LabelAcorde.setText("D#5");
                LabelAcordeName.setText("RE Sostenido Quinta");
            }
            if (Acorde == 4) {
                Limpiar();
                MI1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                LabelAcorde.setText("E5");
                LabelAcordeName.setText("MI Quinta");
            }
            if (Acorde == 5) {
                Limpiar();
                FA1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                LabelAcorde.setText("F5");
                LabelAcordeName.setText("FA Quinta");
            }
            if (Acorde == 6) {
                Limpiar();
                FASos1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                LabelAcorde.setText("F#5");
                LabelAcordeName.setText("FA Sostenido Quinta");
            }
            if (Acorde == 7) {
                Limpiar();
                SOL1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                LabelAcorde.setText("G5");
                LabelAcordeName.setText("SOL Quinta");
            }
            if (Acorde == 8) {
                Limpiar();
                SOLSos1.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                LabelAcorde.setText("G#5");
                LabelAcordeName.setText("SOL Sostenido Quinta");
            }
            if (Acorde == 9) {
                Limpiar();
                LA1.setBackground(ColorTecla);
                MI2.setBackground(ColorTecla);
                LabelAcorde.setText("A5");
                LabelAcordeName.setText("LA Quinta");
            }
            if (Acorde == 10) {
                Limpiar();
                LASos1.setBackground(ColorTecla);
                FA2.setBackground(ColorTecla);
                LabelAcorde.setText("A#5");
                LabelAcordeName.setText("LA Sostenido Quinta");
            }
            if (Acorde == 11) {
                Limpiar();
                SI1.setBackground(ColorTecla);
                FASos2.setBackground(ColorTecla);
                LabelAcorde.setText("B5");
                LabelAcordeName.setText("SI Quinta");
            }
        }

        //Sus2
        if (Familia == 3) {
            if (Acorde == 0) {
                Limpiar();
                DO1.setBackground(ColorTecla);
                RE1.setBackground(ColorTecla);
                SOL1.setBackground(ColorTecla);
                LabelAcorde.setText("Csus2");
                LabelAcordeName.setText("Do Suspendido 2");
            }
            if (Acorde == 1) {
                Limpiar();
                DOSos1.setBackground(ColorTecla);
                RESos1.setBackground(ColorTecla);
                SOLSos1.setBackground(ColorTecla);
                LabelAcorde.setText("C#sus2");
                LabelAcordeName.setText("Do Sostenido Suspendido 2");
            }
            if (Acorde == 2) {
                Limpiar();
                RE1.setBackground(ColorTecla);
                MI1.setBackground(ColorTecla);
                LA1.setBackground(ColorTecla);
                LabelAcorde.setText("Dsus2");
                LabelAcordeName.setText("RE Suspendido 2");
            }
            if (Acorde == 3) {
                Limpiar();
                RESos1.setBackground(ColorTecla);
                FA1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                LabelAcorde.setText("D#sus2");
                LabelAcordeName.setText("RE Sostenido Suspendido 2");
            }
            if (Acorde == 4) {
                Limpiar();
                MI1.setBackground(ColorTecla);
                FASos1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                LabelAcorde.setText("Esus2");
                LabelAcordeName.setText("MI Suspendido 2");
            }
            if (Acorde == 5) {
                Limpiar();
                FA1.setBackground(ColorTecla);
                SOL1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                LabelAcorde.setText("Fsus2");
                LabelAcordeName.setText("FA Suspendido 2");
            }
            if (Acorde == 6) {
                Limpiar();
                FASos1.setBackground(ColorTecla);
                SOLSos1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                LabelAcorde.setText("F#sus2");
                LabelAcordeName.setText("FA Sostenido Suspendido 2");
            }
            if (Acorde == 7) {
                Limpiar();
                SOL1.setBackground(ColorTecla);
                LA1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                LabelAcorde.setText("Gsus2");
                LabelAcordeName.setText("SOL Suspendido 2");
            }
            if (Acorde == 8) {
                Limpiar();
                SOLSos1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                LabelAcorde.setText("G#Sus2");
                LabelAcordeName.setText("SOL Sostenido Suspendido 2");
            }
            if (Acorde == 9) {
                Limpiar();
                LA1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                MI2.setBackground(ColorTecla);
                LabelAcorde.setText("Asus2");
                LabelAcordeName.setText("LA Suspendido 2");
            }
            if (Acorde == 10) {
                Limpiar();
                LASos1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                FA2.setBackground(ColorTecla);
                LabelAcorde.setText("A#sus2");
                LabelAcordeName.setText("LA Sostenido Suspendido 2");
            }
            if (Acorde == 11) {
                Limpiar();
                SI1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                FASos2.setBackground(ColorTecla);
                LabelAcorde.setText("Bsus2");
                LabelAcordeName.setText("SI Suspendido 2");
            }
        }

        //Sus4
        if (Familia == 4) {
            if (Acorde == 0) {
                Limpiar();
                DO1.setBackground(ColorTecla);
                FA1.setBackground(ColorTecla);
                SOL1.setBackground(ColorTecla);
                LabelAcorde.setText("Csus4");
                LabelAcordeName.setText("Do Suspendido 4");
            }
            if (Acorde == 1) {
                Limpiar();
                DOSos1.setBackground(ColorTecla);
                FASos1.setBackground(ColorTecla);
                SOLSos1.setBackground(ColorTecla);
                LabelAcorde.setText("C#sus4");
                LabelAcordeName.setText("Do Sostenido Suspendido 4");
            }
            if (Acorde == 2) {
                Limpiar();
                RE1.setBackground(ColorTecla);
                SOL1.setBackground(ColorTecla);
                LA1.setBackground(ColorTecla);
                LabelAcorde.setText("Dsus4");
                LabelAcordeName.setText("RE Suspendido 4");
            }
            if (Acorde == 3) {
                Limpiar();
                RESos1.setBackground(ColorTecla);
                SOL1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                LabelAcorde.setText("D#sus4");
                LabelAcordeName.setText("RE Sostenido Suspendido 4");
            }
            if (Acorde == 4) {
                Limpiar();
                MI1.setBackground(ColorTecla);
                SOLSos1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                LabelAcorde.setText("Esus4");
                LabelAcordeName.setText("MI Suspendido 4");
            }
            if (Acorde == 5) {
                Limpiar();
                FA1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                LabelAcorde.setText("Fsus4");
                LabelAcordeName.setText("FA Suspendido 4");
            }
            if (Acorde == 6) {
                Limpiar();
                FASos1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                LabelAcorde.setText("F#sus4");
                LabelAcordeName.setText("FA Sostenido Suspendido 4");
            }
            if (Acorde == 7) {
                Limpiar();
                SOL1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                LabelAcorde.setText("Gsus4");
                LabelAcordeName.setText("SOL Suspendido 4");
            }
            if (Acorde == 8) {
                Limpiar();
                SOLSos1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                LabelAcorde.setText("G#Sus4");
                LabelAcordeName.setText("SOL Sostenido Suspendido 4");
            }
            if (Acorde == 9) {
                Limpiar();
                LA1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                MI2.setBackground(ColorTecla);
                LabelAcorde.setText("Asus4");
                LabelAcordeName.setText("LA Suspendido 4");
            }
            if (Acorde == 10) {
                Limpiar();
                LASos1.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                FA2.setBackground(ColorTecla);
                LabelAcorde.setText("A#sus4");
                LabelAcordeName.setText("LA Sostenido Suspendido 4");
            }
            if (Acorde == 11) {
                Limpiar();
                SI1.setBackground(ColorTecla);
                MI2.setBackground(ColorTecla);
                FASos2.setBackground(ColorTecla);
                LabelAcorde.setText("Bsus4");
                LabelAcordeName.setText("SI Suspendido 4");
            }
        }

        //aumentado
        if (Familia == 5) {
            if (Acorde == 0) {

                Limpiar();
                DO1.setBackground(ColorTecla);
                FA1.setBackground(ColorTecla);
                SOLSos1.setBackground(ColorTecla);
                LabelAcorde.setText("Caug");
                LabelAcordeName.setText("Do Aumentado");
            }
            if (Acorde == 1) {
                Limpiar();
                DOSos1.setBackground(ColorTecla);
                FASos1.setBackground(ColorTecla);
                LA1.setBackground(ColorTecla);
                LabelAcorde.setText("C#aug");
                LabelAcordeName.setText("Do Sostenido Aumentado");
            }
            if (Acorde == 2) {
                Limpiar();
                RE1.setBackground(ColorTecla);
                SOL1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                LabelAcorde.setText("Daug");
                LabelAcordeName.setText("RE Aumentado");
            }
            if (Acorde == 3) {
                Limpiar();
                RESos1.setBackground(ColorTecla);
                SOLSos1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                LabelAcorde.setText("D#aug");
                LabelAcordeName.setText("RE Sostenido Aumentado");
            }
            if (Acorde == 4) {
                Limpiar();
                MI1.setBackground(ColorTecla);
                LA1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                LabelAcorde.setText("Eaug");
                LabelAcordeName.setText("MI Aumentado");
            }
            if (Acorde == 5) {
                Limpiar();
                FA1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                LabelAcorde.setText("Faug");
                LabelAcordeName.setText("FA Aumentado");
            }
            if (Acorde == 6) {
                Limpiar();
                FASos1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                LabelAcorde.setText("F#aug");
                LabelAcordeName.setText("FA Sostenido Aumentado");
            }
            if (Acorde == 7) {
                Limpiar();
                SOL1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                LabelAcorde.setText("Gaug");
                LabelAcordeName.setText("SOL Aumentado");
            }
            if (Acorde == 8) {
                Limpiar();
                SOLSos1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                MI2.setBackground(ColorTecla);
                LabelAcorde.setText("G#aug");
                LabelAcordeName.setText("SOL Sostenido Aumentado");
            }
            if (Acorde == 9) {
                Limpiar();
                LA1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                FA2.setBackground(ColorTecla);
                LabelAcorde.setText("Aaug");
                LabelAcordeName.setText("LA Aumentado");
            }
            if (Acorde == 10) {
                Limpiar();
                LASos1.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                FASos2.setBackground(ColorTecla);
                LabelAcorde.setText("A#aug");
                LabelAcordeName.setText("LA Sostenido Aumentado");
            }
            if (Acorde == 11) {
                Limpiar();
                SI1.setBackground(ColorTecla);
                MI2.setBackground(ColorTecla);
                SOL2.setBackground(ColorTecla);
                LabelAcorde.setText("Baug");
                LabelAcordeName.setText("SI Aumentado");
            }
        }

        //disminuido
        if (Familia == 6) {
            if (Acorde == 0) {

                Limpiar();
                DO1.setBackground(ColorTecla);
                RESos1.setBackground(ColorTecla);
                FASos1.setBackground(ColorTecla);
                LabelAcorde.setText("Cdism");
                LabelAcordeName.setText("Do Disminuido");
            }
            if (Acorde == 1) {
                Limpiar();
                DOSos1.setBackground(ColorTecla);
                MI1.setBackground(ColorTecla);
                SOL1.setBackground(ColorTecla);
                LabelAcorde.setText("C#dism");
                LabelAcordeName.setText("Do Sostenido Disminuido");
            }
            if (Acorde == 2) {
                Limpiar();
                RE1.setBackground(ColorTecla);
                FA1.setBackground(ColorTecla);
                SOLSos1.setBackground(ColorTecla);
                LabelAcorde.setText("Ddism");
                LabelAcordeName.setText("RE Disminuido");
            }
            if (Acorde == 3) {
                Limpiar();
                RESos1.setBackground(ColorTecla);
                FASos1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                LabelAcorde.setText("D#dism");
                LabelAcordeName.setText("RE Sostenido Mayor");
            }
            if (Acorde == 4) {
                Limpiar();
                MI1.setBackground(ColorTecla);
                SOL1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                LabelAcorde.setText("Edism");
                LabelAcordeName.setText("MI Disminuido");
            }
            if (Acorde == 5) {
                Limpiar();
                FA1.setBackground(ColorTecla);
                SOLSos1.setBackground(ColorTecla);
                SI2.setBackground(ColorTecla);
                LabelAcorde.setText("Fdism");
                LabelAcordeName.setText("FA Disminuido");
            }
            if (Acorde == 6) {
                Limpiar();
                FASos1.setBackground(ColorTecla);
                LA1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                LabelAcorde.setText("F#dism");
                LabelAcordeName.setText("FA Sostenido Disminuido");
            }
            if (Acorde == 7) {
                Limpiar();
                SOL1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                LabelAcorde.setText("Gdism");
                LabelAcordeName.setText("SOL Disminuido");
            }
            if (Acorde == 8) {
                Limpiar();
                SOLSos1.setBackground(ColorTecla);
                SI2.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                LabelAcorde.setText("G#dism");
                LabelAcordeName.setText("SOL Sostenido Disminuido");
            }
            if (Acorde == 9) {
                Limpiar();
                LA1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                LabelAcorde.setText("Adism");
                LabelAcordeName.setText("LA Disminuido");
            }
            if (Acorde == 10) {
                Limpiar();
                LASos1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                MI2.setBackground(ColorTecla);
                LabelAcorde.setText("A#dism");
                LabelAcordeName.setText("LA Sostenido Disminuido");
            }
            if (Acorde == 11) {
                Limpiar();
                SI1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                FA2.setBackground(ColorTecla);
                LabelAcorde.setText("Bdism");
                LabelAcordeName.setText("SI Disminuido");
            }
        }

        //Septima
        if (Familia == 7) {
            if (Acorde == 0) {
                Limpiar();
                DO1.setBackground(ColorTecla);
                MI1.setBackground(ColorTecla);
                SOL1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                LabelAcorde.setText("C7");
                LabelAcordeName.setText("Do septima");
            }
            if (Acorde == 1) {
                Limpiar();
                DOSos1.setBackground(ColorTecla);
                FA1.setBackground(ColorTecla);
                SOLSos1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                LabelAcorde.setText("C#7");
                LabelAcordeName.setText("Do Sostenido septima");
            }
            if (Acorde == 2) {
                Limpiar();
                RE1.setBackground(ColorTecla);
                FASos1.setBackground(ColorTecla);
                LA1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                LabelAcorde.setText("D7");
                LabelAcordeName.setText("RE septima");
            }
            if (Acorde == 3) {
                Limpiar();
                RESos1.setBackground(ColorTecla);
                SOL1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                LabelAcorde.setText("D#7");
                LabelAcordeName.setText("RE Sostenido septima");
            }
            if (Acorde == 4) {
                Limpiar();
                MI1.setBackground(ColorTecla);
                SOLSos1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                LabelAcorde.setText("E7");
                LabelAcordeName.setText("MI septima");
            }
            if (Acorde == 5) {
                Limpiar();
                FA1.setBackground(ColorTecla);
                LA1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                LabelAcorde.setText("F7");
                LabelAcordeName.setText("FA septima");
            }
            if (Acorde == 6) {
                Limpiar();
                FASos1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                MI2.setBackground(ColorTecla);
                LabelAcorde.setText("F#7");
                LabelAcordeName.setText("FA Sostenido septima");
            }
            if (Acorde == 7) {
                Limpiar();
                SOL1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                FA2.setBackground(ColorTecla);
                LabelAcorde.setText("G7");
                LabelAcordeName.setText("SOL septima");
            }
            if (Acorde == 8) {
                Limpiar();
                SOLSos1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                FASos2.setBackground(ColorTecla);
                LabelAcorde.setText("G#7");
                LabelAcordeName.setText("SOL Sostenido septima");
            }
            if (Acorde == 9) {
                Limpiar();
                LA1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                MI2.setBackground(ColorTecla);
                SOL2.setBackground(ColorTecla);
                LabelAcorde.setText("A7");
                LabelAcordeName.setText("LA septima");
            }
            if (Acorde == 10) {
                Limpiar();
                LASos1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                FA2.setBackground(ColorTecla);
                SOLSos2.setBackground(ColorTecla);
                LabelAcorde.setText("A#7");
                LabelAcordeName.setText("LA Sostenido septima");
            }
            if (Acorde == 11) {
                Limpiar();
                SI1.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                FASos2.setBackground(ColorTecla);
                LA2.setBackground(ColorTecla);
                LabelAcorde.setText("B7");
                LabelAcordeName.setText("SI septima");
            }
        }

        //Octava
        if (Familia == 8) {
            if (Acorde == 0) {
                Limpiar();
                DO1.setBackground(ColorTecla);
                SOL1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                LabelAcorde.setText("C");
                LabelAcordeName.setText("Do Octava");
            }
            if (Acorde == 1) {
                Limpiar();
                DOSos1.setBackground(ColorTecla);
                SOLSos1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                LabelAcorde.setText("C#");
                LabelAcordeName.setText("Do Sostenido Octava");
            }
            if (Acorde == 2) {
                Limpiar();
                RE1.setBackground(ColorTecla);
                LA1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                LabelAcorde.setText("D");
                LabelAcordeName.setText("RE Octava");
            }
            if (Acorde == 3) {
                Limpiar();
                RESos1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                LabelAcorde.setText("D#");
                LabelAcordeName.setText("RE Sostenido Octava");
            }
            if (Acorde == 4) {
                Limpiar();
                MI1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                MI2.setBackground(ColorTecla);
                LabelAcorde.setText("E");
                LabelAcordeName.setText("MI Octava");
            }
            if (Acorde == 5) {
                Limpiar();
                FA1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                FA2.setBackground(ColorTecla);
                LabelAcorde.setText("F");
                LabelAcordeName.setText("FA Octava");
            }
            if (Acorde == 6) {
                Limpiar();
                FASos1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                FASos2.setBackground(ColorTecla);
                LabelAcorde.setText("F#");
                LabelAcordeName.setText("FA Sostenido Octava");
            }
            if (Acorde == 7) {
                Limpiar();
                SOL1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                SOL2.setBackground(ColorTecla);
                LabelAcorde.setText("G");
                LabelAcordeName.setText("SOL Octava");
            }
            if (Acorde == 8) {
                Limpiar();
                SOLSos1.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                SOLSos2.setBackground(ColorTecla);
                LabelAcorde.setText("G#m");
                LabelAcordeName.setText("SOL Sostenido Octava");
            }
            if (Acorde == 9) {
                Limpiar();
                LA1.setBackground(ColorTecla);
                MI2.setBackground(ColorTecla);
                LA2.setBackground(ColorTecla);
                LabelAcorde.setText("A");
                LabelAcordeName.setText("LA Octava");
            }
            if (Acorde == 10) {
                Limpiar();
                LASos1.setBackground(ColorTecla);
                FA2.setBackground(ColorTecla);
                LASos2.setBackground(ColorTecla);
                LabelAcorde.setText("A#");
                LabelAcordeName.setText("LA Sostenido Octava");
            }
            if (Acorde == 11) {
                Limpiar();
                SI1.setBackground(ColorTecla);
                FASos2.setBackground(ColorTecla);
                SI2.setBackground(ColorTecla);
                LabelAcorde.setText("B");
                LabelAcordeName.setText("SI Octava");
            }
        }

        //novena
        if (Familia == 9) {
            if (Acorde == 0) {
                Limpiar();
                DO1.setBackground(ColorTecla);
                MI1.setBackground(ColorTecla);
                SOL1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                LabelAcorde.setText("C9");
                LabelAcordeName.setText("Do novena");
            }
            if (Acorde == 1) {
                Limpiar();
                DOSos1.setBackground(ColorTecla);
                FA1.setBackground(ColorTecla);
                SOLSos1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                LabelAcorde.setText("C#9");
                LabelAcordeName.setText("Do Sostenido novena");
            }
            if (Acorde == 2) {
                Limpiar();
                RE1.setBackground(ColorTecla);
                FASos1.setBackground(ColorTecla);
                LA1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                MI2.setBackground(ColorTecla);
                LabelAcorde.setText("D9");
                LabelAcordeName.setText("RE novena");
            }
            if (Acorde == 3) {
                Limpiar();
                RESos1.setBackground(ColorTecla);
                SOL1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                FA2.setBackground(ColorTecla);
                LabelAcorde.setText("D#9");
                LabelAcordeName.setText("RE Sostenido novena");
            }
            if (Acorde == 4) {
                Limpiar();
                MI1.setBackground(ColorTecla);
                SOLSos1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                FASos2.setBackground(ColorTecla);
                LabelAcorde.setText("E9");
                LabelAcordeName.setText("MI novena");
            }
            if (Acorde == 5) {
                Limpiar();
                FA1.setBackground(ColorTecla);
                LA1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                SOL2.setBackground(ColorTecla);
                LabelAcorde.setText("F9");
                LabelAcordeName.setText("FA novena");
            }
            if (Acorde == 6) {
                Limpiar();
                FASos1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                MI2.setBackground(ColorTecla);
                SOLSos2.setBackground(ColorTecla);
                LabelAcorde.setText("F#9");
                LabelAcordeName.setText("FA Sostenido novena");
            }
            if (Acorde == 7) {
                Limpiar();
                SOL1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                FA2.setBackground(ColorTecla);
                LA2.setBackground(ColorTecla);
                LabelAcorde.setText("G9");
                LabelAcordeName.setText("SOL novena");
            }
            if (Acorde == 8) {
                Limpiar();
                SOLSos1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                FASos2.setBackground(ColorTecla);
                LASos2.setBackground(ColorTecla);
                LabelAcorde.setText("G#9");
                LabelAcordeName.setText("SOL Sostenido novena");
            }
            if (Acorde == 9) {
                Limpiar();
                LA1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                MI2.setBackground(ColorTecla);
                SOL2.setBackground(ColorTecla);
                SI2.setBackground(ColorTecla);
                LabelAcorde.setText("A9");
                LabelAcordeName.setText("LA novena");
            }
            if (Acorde == 10) {
                Limpiar();
                LASos1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                FA2.setBackground(ColorTecla);
                SOLSos2.setBackground(ColorTecla);
                DO3.setBackground(ColorTecla);
                LabelAcorde.setText("A#9");
                LabelAcordeName.setText("LA Sostenido novena");
            }
            if (Acorde == 11) {
                Limpiar();
                SI1.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                FASos2.setBackground(ColorTecla);
                LA2.setBackground(ColorTecla);
                DOSos3.setBackground(ColorTecla);
                LabelAcorde.setText("B9");
                LabelAcordeName.setText("SI novena");
            }
        }

        //Maj6
        if (Familia == 10) {
            if (Acorde == 0) {
                Limpiar();
                DO1.setBackground(ColorTecla);
                MI1.setBackground(ColorTecla);
                SOL1.setBackground(ColorTecla);
                LA1.setBackground(ColorTecla);
                LabelAcorde.setText("Cmaj6");
                LabelAcordeName.setText("Do con sexta añadida");
            }
            if (Acorde == 1) {
                Limpiar();
                DOSos1.setBackground(ColorTecla);
                FA1.setBackground(ColorTecla);
                SOLSos1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                LabelAcorde.setText("C#maj6");
                LabelAcordeName.setText("Do Sostenido con sexta añadida");
            }
            if (Acorde == 2) {
                Limpiar();
                RE1.setBackground(ColorTecla);
                FASos1.setBackground(ColorTecla);
                LA1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                LabelAcorde.setText("Dmaj6");
                LabelAcordeName.setText("RE con sexta añadida");
            }
            if (Acorde == 3) {
                Limpiar();
                RESos1.setBackground(ColorTecla);
                SOL1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                LabelAcorde.setText("D#maj6");
                LabelAcordeName.setText("RE Sostenido con sexta añadida");
            }
            if (Acorde == 4) {
                Limpiar();
                MI1.setBackground(ColorTecla);
                SOLSos1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                LabelAcorde.setText("Emaj6");
                LabelAcordeName.setText("MI con sexta añadida");
            }
            if (Acorde == 5) {
                Limpiar();
                FA1.setBackground(ColorTecla);
                LA1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                LabelAcorde.setText("Fmaj6");
                LabelAcordeName.setText("FA con sexta añadida");
            }
            if (Acorde == 6) {
                Limpiar();
                FASos1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                LabelAcorde.setText("F#maj6");
                LabelAcordeName.setText("FA Sostenido con sexta añadida");
            }
            if (Acorde == 7) {
                Limpiar();
                SOL1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                MI2.setBackground(ColorTecla);
                LabelAcorde.setText("Gmaj7");
                LabelAcordeName.setText("SOL con sexta añadida");
            }
            if (Acorde == 8) {
                Limpiar();
                SOLSos1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                FA2.setBackground(ColorTecla);
                LabelAcorde.setText("G#maj6");
                LabelAcordeName.setText("SOL Sostenido con sexta añadida");
            }
            if (Acorde == 9) {
                Limpiar();
                LA1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                MI2.setBackground(ColorTecla);
                FASos2.setBackground(ColorTecla);
                LabelAcorde.setText("Amaj6");
                LabelAcordeName.setText("LA con septima añadida");
            }
            if (Acorde == 10) {
                Limpiar();
                LASos1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                FA2.setBackground(ColorTecla);
                SOL2.setBackground(ColorTecla);
                LabelAcorde.setText("A#maj6");
                LabelAcordeName.setText("LA Sostenido con sexta añadida");
            }
            if (Acorde == 11) {
                Limpiar();
                SI1.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                FASos2.setBackground(ColorTecla);
                SOLSos2.setBackground(ColorTecla);
                LabelAcorde.setText("Bmaj6");
                LabelAcordeName.setText("SI con sexta añadida");
            }
        }

        //Maj7
        if (Familia == 11) {
            if (Acorde == 0) {
                Limpiar();
                DO1.setBackground(ColorTecla);
                MI1.setBackground(ColorTecla);
                SOL1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                LabelAcorde.setText("Cmaj7");
                LabelAcordeName.setText("Do con septima añadida");
            }
            if (Acorde == 1) {
                Limpiar();
                DOSos1.setBackground(ColorTecla);
                FA1.setBackground(ColorTecla);
                SOLSos1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                LabelAcorde.setText("C#maj7");
                LabelAcordeName.setText("Do Sostenido con septima añadida");
            }
            if (Acorde == 2) {
                Limpiar();
                RE1.setBackground(ColorTecla);
                FASos1.setBackground(ColorTecla);
                LA1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                LabelAcorde.setText("Dmaj7");
                LabelAcordeName.setText("RE con septima añadida");
            }
            if (Acorde == 3) {
                Limpiar();
                RESos1.setBackground(ColorTecla);
                SOL1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                LabelAcorde.setText("D#maj7");
                LabelAcordeName.setText("RE Sostenido con septima añadida");
            }
            if (Acorde == 4) {
                Limpiar();
                MI1.setBackground(ColorTecla);
                SOLSos1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                LabelAcorde.setText("Emaj7");
                LabelAcordeName.setText("MI con septima añadida");
            }
            if (Acorde == 5) {
                Limpiar();
                FA1.setBackground(ColorTecla);
                LA1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                MI2.setBackground(ColorTecla);
                LabelAcorde.setText("Fmaj7");
                LabelAcordeName.setText("FA con septima añadida");
            }
            if (Acorde == 6) {
                Limpiar();
                FASos1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                FA2.setBackground(ColorTecla);
                LabelAcorde.setText("F#maj7");
                LabelAcordeName.setText("FA Sostenido con septima añadida");
            }
            if (Acorde == 7) {
                Limpiar();
                SOL1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                FASos2.setBackground(ColorTecla);
                LabelAcorde.setText("Gmaj7");
                LabelAcordeName.setText("SOL con septima añadida");
            }
            if (Acorde == 8) {
                Limpiar();
                SOLSos1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                SOL2.setBackground(ColorTecla);
                LabelAcorde.setText("G#maj7");
                LabelAcordeName.setText("SOL Sostenido con septima añadida");
            }
            if (Acorde == 9) {
                Limpiar();
                LA1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                MI2.setBackground(ColorTecla);
                SOLSos2.setBackground(ColorTecla);
                LabelAcorde.setText("Amaj7");
                LabelAcordeName.setText("LA con septima añadida");
            }
            if (Acorde == 10) {
                Limpiar();
                LASos1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                FA2.setBackground(ColorTecla);
                LA2.setBackground(ColorTecla);
                LabelAcorde.setText("A#maj7");
                LabelAcordeName.setText("LA Sostenido con septima añadida");
            }
            if (Acorde == 11) {
                Limpiar();
                SI1.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                FASos2.setBackground(ColorTecla);
                LASos2.setBackground(ColorTecla);
                LabelAcorde.setText("Bmaj7");
                LabelAcordeName.setText("SI con septima añadida");
            }
        }

        //maj9
        if (Familia == 12) {
            if (Acorde == 0) {
                Limpiar();
                DO1.setBackground(ColorTecla);
                MI1.setBackground(ColorTecla);
                SOL1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                LabelAcorde.setText("Cmaj9");
                LabelAcordeName.setText("Do con novena añadida");
            }
            if (Acorde == 1) {
                Limpiar();
                DOSos1.setBackground(ColorTecla);
                FA1.setBackground(ColorTecla);
                SOLSos1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                LabelAcorde.setText("C#maj9");
                LabelAcordeName.setText("Do Sostenido con novena añadida");
            }
            if (Acorde == 2) {
                Limpiar();
                RE1.setBackground(ColorTecla);
                FASos1.setBackground(ColorTecla);
                LA1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                MI2.setBackground(ColorTecla);
                LabelAcorde.setText("Dmaj9");
                LabelAcordeName.setText("RE con novena añadida");
            }
            if (Acorde == 3) {
                Limpiar();
                RESos1.setBackground(ColorTecla);
                SOL1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                FA2.setBackground(ColorTecla);
                LabelAcorde.setText("D#maj9");
                LabelAcordeName.setText("RE Sostenido con novena añadida");
            }
            if (Acorde == 4) {
                Limpiar();
                MI1.setBackground(ColorTecla);
                SOLSos1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                FASos2.setBackground(ColorTecla);
                LabelAcorde.setText("Emaj9");
                LabelAcordeName.setText("MI con novena añadida");
            }
            if (Acorde == 5) {
                Limpiar();
                FA1.setBackground(ColorTecla);
                LA1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                MI2.setBackground(ColorTecla);
                SOL2.setBackground(ColorTecla);
                LabelAcorde.setText("Fmaj9");
                LabelAcordeName.setText("FA con novena añadida");
            }
            if (Acorde == 6) {
                Limpiar();
                FASos1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                FA2.setBackground(ColorTecla);
                SOLSos2.setBackground(ColorTecla);
                LabelAcorde.setText("F#maj9");
                LabelAcordeName.setText("FA Sostenido con novena añadida");
            }
            if (Acorde == 7) {
                Limpiar();
                SOL1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                FASos2.setBackground(ColorTecla);
                LA2.setBackground(ColorTecla);
                LabelAcorde.setText("Gmaj9");
                LabelAcordeName.setText("SOLcon  novena añadida");
            }
            if (Acorde == 8) {
                Limpiar();
                SOLSos1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                SOL2.setBackground(ColorTecla);
                LASos2.setBackground(ColorTecla);
                LabelAcorde.setText("G#maj9");
                LabelAcordeName.setText("SOL Sostenido con novena añadida");
            }
            if (Acorde == 9) {
                Limpiar();
                LA1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                MI2.setBackground(ColorTecla);
                SOLSos2.setBackground(ColorTecla);
                SI2.setBackground(ColorTecla);
                LabelAcorde.setText("Amaj9");
                LabelAcordeName.setText("LA co novena añadida");
            }
            if (Acorde == 10) {
                Limpiar();
                LASos1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                FA2.setBackground(ColorTecla);
                LA2.setBackground(ColorTecla);
                DO3.setBackground(ColorTecla);
                LabelAcorde.setText("A#maj9");
                LabelAcordeName.setText("LA Sostenido con novena añadida");
            }
            if (Acorde == 11) {
                Limpiar();
                SI1.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                FASos2.setBackground(ColorTecla);
                LASos2.setBackground(ColorTecla);
                DOSos3.setBackground(ColorTecla);
                LabelAcorde.setText("Bmaj9");
                LabelAcordeName.setText("SI con novena añadida");
            }
        }

        //Maj11
        if (Familia == 13) {
            if (Acorde == 0) {
                Limpiar();
                DO1.setBackground(ColorTecla);
                MI1.setBackground(ColorTecla);
                SOL1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                FA2.setBackground(ColorTecla);
                LabelAcorde.setText("Cmaj11");
                LabelAcordeName.setText("Do con onceaba añadida");
            }
            if (Acorde == 1) {
                Limpiar();
                DOSos1.setBackground(ColorTecla);
                FA1.setBackground(ColorTecla);
                SOLSos1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                FASos2.setBackground(ColorTecla);
                LabelAcorde.setText("C#maj11");
                LabelAcordeName.setText("Do Sostenido con onceaba añadida");
            }
            if (Acorde == 2) {
                Limpiar();
                RE1.setBackground(ColorTecla);
                FASos1.setBackground(ColorTecla);
                LA1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                SOL2.setBackground(ColorTecla);
                LabelAcorde.setText("Dmaj11");
                LabelAcordeName.setText("RE con onceaba añadida");
            }
            if (Acorde == 3) {
                Limpiar();
                RESos1.setBackground(ColorTecla);
                SOL1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                SOLSos3.setBackground(ColorTecla);
                LabelAcorde.setText("D#maj11");
                LabelAcordeName.setText("RE Sostenido con onceaba añadida");
            }
            if (Acorde == 4) {
                Limpiar();
                MI1.setBackground(ColorTecla);
                SOLSos1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                LA3.setBackground(ColorTecla);
                LabelAcorde.setText("Emaj11");
                LabelAcordeName.setText("MI con onceaba añadida");
            }
            if (Acorde == 5) {
                Limpiar();
                FA1.setBackground(ColorTecla);
                LA1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                MI2.setBackground(ColorTecla);
                LASos3.setBackground(ColorTecla);
                LabelAcorde.setText("Fmaj11");
                LabelAcordeName.setText("FA con onceaba añadida");
            }
            if (Acorde == 6) {
                Limpiar();
                FASos1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                FA2.setBackground(ColorTecla);
                SI2.setBackground(ColorTecla);
                LabelAcorde.setText("F#maj11");
                LabelAcordeName.setText("FA Sostenido con onceba añadida");
            }
            if (Acorde == 7) {
                Limpiar();
                SOL1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                FASos2.setBackground(ColorTecla);
                DO3.setBackground(ColorTecla);
                LabelAcorde.setText("Gmaj11");
                LabelAcordeName.setText("SOL con onceaba añadida");
            }
            if (Acorde == 8) {
                Limpiar();
                SOLSos1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                SOL2.setBackground(ColorTecla);
                DOSos3.setBackground(ColorTecla);
                LabelAcorde.setText("G#maj11");
                LabelAcordeName.setText("SOL Sostenido con onceaba añadida");
            }
            if (Acorde == 9) {
                Limpiar();
                LA1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                MI2.setBackground(ColorTecla);
                SOLSos2.setBackground(ColorTecla);
                RE3.setBackground(ColorTecla);
                LabelAcorde.setText("Amaj11");
                LabelAcordeName.setText("LA con onceaba añadida");
            }
            if (Acorde == 10) {
                Limpiar();
                LASos1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                FA2.setBackground(ColorTecla);
                LA2.setBackground(ColorTecla);
                RESos3.setBackground(ColorTecla);
                LabelAcorde.setText("A#maj11");
                LabelAcordeName.setText("LA Sostenido con onceaba añadida");
            }
            if (Acorde == 11) {
                Limpiar();
                SI1.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                FASos2.setBackground(ColorTecla);
                LASos2.setBackground(ColorTecla);
                MI3.setBackground(ColorTecla);
                LabelAcorde.setText("Bmaj11");
                LabelAcordeName.setText("SI con onceaba añadida");
            }
        }

        //Maj13
        if (Familia == 14) {
            if (Acorde == 0) {
                Limpiar();
                DO1.setBackground(ColorTecla);
                MI1.setBackground(ColorTecla);
                SOL1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                LA2.setBackground(ColorTecla);
                LabelAcorde.setText("Cmaj13");
                LabelAcordeName.setText("Do con treceaba añadida");
            }
            if (Acorde == 1) {
                Limpiar();
                DOSos1.setBackground(ColorTecla);
                FA1.setBackground(ColorTecla);
                SOLSos1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                LASos2.setBackground(ColorTecla);
                LabelAcorde.setText("C#maj13");
                LabelAcordeName.setText("Do Sostenido con treceaba añadida");
            }
            if (Acorde == 2) {
                Limpiar();
                RE1.setBackground(ColorTecla);
                FASos1.setBackground(ColorTecla);
                LA1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                SI2.setBackground(ColorTecla);
                LabelAcorde.setText("Dmaj13");
                LabelAcordeName.setText("RE con treceaba añadida");
            }
            if (Acorde == 3) {
                Limpiar();
                RESos1.setBackground(ColorTecla);
                SOL1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                DO3.setBackground(ColorTecla);
                LabelAcorde.setText("D#maj13");
                LabelAcordeName.setText("RE Sostenido con treceaba añadida");
            }
            if (Acorde == 4) {
                Limpiar();
                MI1.setBackground(ColorTecla);
                SOLSos1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                DOSos3.setBackground(ColorTecla);
                LabelAcorde.setText("Emaj13");
                LabelAcordeName.setText("MI con treceaba añadida");
            }
            if (Acorde == 5) {
                Limpiar();
                FA1.setBackground(ColorTecla);
                LA1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                MI2.setBackground(ColorTecla);
                RE3.setBackground(ColorTecla);
                LabelAcorde.setText("Fmaj13");
                LabelAcordeName.setText("FA con treceaba añadida");
            }
            if (Acorde == 6) {
                Limpiar();
                FASos1.setBackground(ColorTecla);
                LASos1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                FA2.setBackground(ColorTecla);
                RESos3.setBackground(ColorTecla);
                LabelAcorde.setText("F#maj13");
                LabelAcordeName.setText("FA Sostenido con treceaba añadida");
            }
            if (Acorde == 7) {
                Limpiar();
                SOL1.setBackground(ColorTecla);
                SI1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                FASos2.setBackground(ColorTecla);
                MI3.setBackground(ColorTecla);
                LabelAcorde.setText("Gmaj13");
                LabelAcordeName.setText("SOL con treceaba añadida");
            }
            if (Acorde == 8) {
                Limpiar();
                SOLSos1.setBackground(ColorTecla);
                DO2.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                SOL2.setBackground(ColorTecla);
                FA3.setBackground(ColorTecla);
                LabelAcorde.setText("G#maj13");
                LabelAcordeName.setText("SOL Sostenido con treceaba añadida");
            }
            if (Acorde == 9) {
                Limpiar();
                LA1.setBackground(ColorTecla);
                DOSos2.setBackground(ColorTecla);
                MI2.setBackground(ColorTecla);
                SOLSos2.setBackground(ColorTecla);
                FASos3.setBackground(ColorTecla);
                LabelAcorde.setText("Amaj13");
                LabelAcordeName.setText("LA con treceaba añadida");
            }
            if (Acorde == 10) {
                Limpiar();
                LASos1.setBackground(ColorTecla);
                RE2.setBackground(ColorTecla);
                FA2.setBackground(ColorTecla);
                LA2.setBackground(ColorTecla);
                SOL3.setBackground(ColorTecla);
                LabelAcorde.setText("A#maj13");
                LabelAcordeName.setText("LA Sostenido con treceaba añadida");
            }
            if (Acorde == 11) {
                Limpiar();
                SI1.setBackground(ColorTecla);
                RESos2.setBackground(ColorTecla);
                FASos2.setBackground(ColorTecla);
                LASos2.setBackground(ColorTecla);
                SOLSos3.setBackground(ColorTecla);
                LabelAcorde.setText("Bmaj13");
                LabelAcordeName.setText("SI con treceaba añadida");
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acordes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acordes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acordes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acordes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acordes().setVisible(true);
            }
        });
    }

    public void Limpiar() {
        DO1.setBackground(Color.WHITE);
        DOSos1.setBackground(Color.BLACK);
        RE1.setBackground(Color.WHITE);
        RESos1.setBackground(Color.BLACK);
        MI1.setBackground(Color.WHITE);
        FA1.setBackground(Color.WHITE);
        FASos1.setBackground(Color.BLACK);
        SOL1.setBackground(Color.WHITE);
        SOLSos1.setBackground(Color.BLACK);
        LA1.setBackground(Color.WHITE);
        LASos1.setBackground(Color.BLACK);
        SI1.setBackground(Color.WHITE);
        DO2.setBackground(Color.WHITE);
        DOSos2.setBackground(Color.BLACK);
        RE2.setBackground(Color.WHITE);
        RESos2.setBackground(Color.BLACK);
        MI2.setBackground(Color.WHITE);
        FA2.setBackground(Color.WHITE);
        FASos2.setBackground(Color.BLACK);
        SOL2.setBackground(Color.WHITE);
        SOLSos2.setBackground(Color.BLACK);
        LA2.setBackground(Color.WHITE);
        LASos2.setBackground(Color.BLACK);
        SI2.setBackground(Color.WHITE);
        DO3.setBackground(Color.WHITE);
        DOSos3.setBackground(Color.BLACK);
        RE3.setBackground(Color.WHITE);
        RESos3.setBackground(Color.BLACK);
        MI3.setBackground(Color.WHITE);
        FA3.setBackground(Color.WHITE);
        FASos3.setBackground(Color.BLACK);
        SOL3.setBackground(Color.WHITE);
        SOLSos3.setBackground(Color.BLACK);
        LA3.setBackground(Color.WHITE);
        LASos3.setBackground(Color.BLACK);
        SI3.setBackground(Color.WHITE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbAcorde;
    private javax.swing.JComboBox<String> CmbFamilia;
    private javax.swing.JButton DO1;
    private javax.swing.JButton DO2;
    private javax.swing.JButton DO3;
    private javax.swing.JButton DOSos1;
    private javax.swing.JButton DOSos2;
    private javax.swing.JButton DOSos3;
    private javax.swing.JButton FA1;
    private javax.swing.JButton FA2;
    private javax.swing.JButton FA3;
    private javax.swing.JButton FASos1;
    private javax.swing.JButton FASos2;
    private javax.swing.JButton FASos3;
    private javax.swing.JButton LA1;
    private javax.swing.JButton LA2;
    private javax.swing.JButton LA3;
    private javax.swing.JButton LASos1;
    private javax.swing.JButton LASos2;
    private javax.swing.JButton LASos3;
    private javax.swing.JLabel LabelAcorde;
    private javax.swing.JLabel LabelAcordeName;
    private javax.swing.JLabel LabelWallpaper;
    private javax.swing.JButton MI1;
    private javax.swing.JButton MI2;
    private javax.swing.JButton MI3;
    private javax.swing.JButton RE1;
    private javax.swing.JButton RE2;
    private javax.swing.JButton RE3;
    private javax.swing.JButton RESos1;
    private javax.swing.JButton RESos2;
    private javax.swing.JButton RESos3;
    private javax.swing.JButton SI1;
    private javax.swing.JButton SI2;
    private javax.swing.JButton SI3;
    private javax.swing.JButton SOL1;
    private javax.swing.JButton SOL2;
    private javax.swing.JButton SOL3;
    private javax.swing.JButton SOLSos1;
    private javax.swing.JButton SOLSos2;
    private javax.swing.JButton SOLSos3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
