/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author MINEDUCYT
 */
public class AcordesGuitarra extends javax.swing.JFrame {

    /**
     * Creates new form Acordes
     */
    public AcordesGuitarra() {
        initComponents();

        this.setLocationRelativeTo(null);

        ImageIcon wallpaper = new ImageIcon("src/img/wallpaperGuitarra.jpg");
        Icon icon = new ImageIcon(wallpaper.getImage().getScaledInstance(LabelWallpaper.getWidth(),
                LabelWallpaper.getHeight(), Image.SCALE_DEFAULT));

        LabelWallpaper.setIcon(icon);
        Limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CmbAcorde = new javax.swing.JComboBox<>();
        CmbFamilia = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        LabelAcorde = new javax.swing.JLabel();
        LabelAcordeName = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        NTraste = new javax.swing.JTextField();
        NCuerda1 = new javax.swing.JTextField();
        NCuerda2 = new javax.swing.JTextField();
        NCuerda3 = new javax.swing.JTextField();
        NCuerda4 = new javax.swing.JTextField();
        NCuerda5 = new javax.swing.JTextField();
        NCuerda6 = new javax.swing.JTextField();
        Espacio4 = new javax.swing.JTextField();
        Espacio3 = new javax.swing.JTextField();
        Espacio2 = new javax.swing.JTextField();
        Espacio1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        Cuerdas = new javax.swing.JPanel();
        Puente3 = new javax.swing.JTextArea();
        Puente2 = new javax.swing.JTextArea();
        Puente1 = new javax.swing.JTextArea();
        Clavijero = new javax.swing.JTextArea();
        Dedos1 = new javax.swing.JLabel();
        Dedos2 = new javax.swing.JLabel();
        Dedos3 = new javax.swing.JLabel();
        Dedos4 = new javax.swing.JLabel();
        Dedos5 = new javax.swing.JLabel();
        Dedos6 = new javax.swing.JLabel();
        Dedos7 = new javax.swing.JLabel();
        Dedos8 = new javax.swing.JLabel();
        Dedos9 = new javax.swing.JLabel();
        Dedos10 = new javax.swing.JLabel();
        Dedos11 = new javax.swing.JLabel();
        Dedos12 = new javax.swing.JLabel();
        Dedos13 = new javax.swing.JLabel();
        Dedos14 = new javax.swing.JLabel();
        Dedos15 = new javax.swing.JLabel();
        Dedos16 = new javax.swing.JLabel();
        Dedos17 = new javax.swing.JLabel();
        Dedos18 = new javax.swing.JLabel();
        Dedos19 = new javax.swing.JLabel();
        Dedos20 = new javax.swing.JLabel();
        Dedos21 = new javax.swing.JLabel();
        Dedos22 = new javax.swing.JLabel();
        Dedos23 = new javax.swing.JLabel();
        Dedos24 = new javax.swing.JLabel();
        Traste1 = new javax.swing.JTextArea();
        Traste2 = new javax.swing.JTextArea();
        Traste3 = new javax.swing.JTextArea();
        Cuerda1 = new javax.swing.JLabel();
        Cuerda2 = new javax.swing.JLabel();
        Cuerda3 = new javax.swing.JLabel();
        Cuerda4 = new javax.swing.JLabel();
        Cuerda5 = new javax.swing.JLabel();
        Cuerda6 = new javax.swing.JLabel();
        LabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CmbAcorde.setBackground(new java.awt.Color(51, 51, 51));
        CmbAcorde.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        CmbAcorde.setForeground(new java.awt.Color(255, 255, 255));
        CmbAcorde.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DO", "DO#", "RE", "RE#", "MI", "FA", "FA#", "SOL", "SOL#", "LA", "LA#", "SI" }));
        CmbAcorde.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(CmbAcorde, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 210, 40));

        CmbFamilia.setBackground(new java.awt.Color(51, 51, 51));
        CmbFamilia.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        CmbFamilia.setForeground(new java.awt.Color(255, 255, 255));
        CmbFamilia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mayor", "Menor" }));
        CmbFamilia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(CmbFamilia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 250, 40));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Generar");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 119, 40));

        LabelAcorde.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        LabelAcorde.setForeground(new java.awt.Color(255, 255, 255));
        LabelAcorde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelAcorde.setText("ACORDE");
        getContentPane().add(LabelAcorde, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 418, 430, -1));

        LabelAcordeName.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        LabelAcordeName.setForeground(new java.awt.Color(255, 255, 255));
        LabelAcordeName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelAcordeName.setText("Nombre del Acorde");
        getContentPane().add(LabelAcordeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 476, 430, -1));

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(51, 51, 51));
        jTextField7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 450, 90));

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(51, 51, 51));
        jTextField8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setText("Acorde");
        jTextField8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 80, 30));
        jTextField8.getAccessibleContext().setAccessibleName("");

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(51, 51, 51));
        jTextField9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 255, 255));
        jTextField9.setText("Familia");
        jTextField9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 80, 30));

        NTraste.setEditable(false);
        NTraste.setBackground(new java.awt.Color(51, 51, 51));
        NTraste.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        NTraste.setForeground(new java.awt.Color(255, 255, 255));
        NTraste.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NTraste.setText("Traste:");
        NTraste.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(NTraste, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 70, 30));

        NCuerda1.setEditable(false);
        NCuerda1.setBackground(new java.awt.Color(51, 51, 51));
        NCuerda1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        NCuerda1.setForeground(new java.awt.Color(255, 255, 255));
        NCuerda1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NCuerda1.setText("Cuerda6 (E)");
        NCuerda1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(NCuerda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 110, 30));

        NCuerda2.setEditable(false);
        NCuerda2.setBackground(new java.awt.Color(51, 51, 51));
        NCuerda2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        NCuerda2.setForeground(new java.awt.Color(255, 255, 255));
        NCuerda2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NCuerda2.setText("Cuerda1 (E)");
        NCuerda2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(NCuerda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 110, 30));

        NCuerda3.setEditable(false);
        NCuerda3.setBackground(new java.awt.Color(51, 51, 51));
        NCuerda3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        NCuerda3.setForeground(new java.awt.Color(255, 255, 255));
        NCuerda3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NCuerda3.setText("Cuerda2 (B)");
        NCuerda3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(NCuerda3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 110, 30));

        NCuerda4.setEditable(false);
        NCuerda4.setBackground(new java.awt.Color(51, 51, 51));
        NCuerda4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        NCuerda4.setForeground(new java.awt.Color(255, 255, 255));
        NCuerda4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NCuerda4.setText("Cuerda3 (G)");
        NCuerda4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(NCuerda4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 110, 30));

        NCuerda5.setEditable(false);
        NCuerda5.setBackground(new java.awt.Color(51, 51, 51));
        NCuerda5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        NCuerda5.setForeground(new java.awt.Color(255, 255, 255));
        NCuerda5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NCuerda5.setText("Cuerda4 (D)");
        NCuerda5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(NCuerda5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 110, 30));

        NCuerda6.setEditable(false);
        NCuerda6.setBackground(new java.awt.Color(51, 51, 51));
        NCuerda6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        NCuerda6.setForeground(new java.awt.Color(255, 255, 255));
        NCuerda6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NCuerda6.setText("Cuerda5 (A)");
        NCuerda6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(NCuerda6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 110, 30));

        Espacio4.setEditable(false);
        Espacio4.setBackground(new java.awt.Color(51, 51, 51));
        Espacio4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Espacio4.setForeground(new java.awt.Color(255, 255, 255));
        Espacio4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Espacio4.setText("4");
        Espacio4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Espacio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 30, 30));

        Espacio3.setEditable(false);
        Espacio3.setBackground(new java.awt.Color(51, 51, 51));
        Espacio3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Espacio3.setForeground(new java.awt.Color(255, 255, 255));
        Espacio3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Espacio3.setText("3");
        Espacio3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Espacio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 30, 30));

        Espacio2.setEditable(false);
        Espacio2.setBackground(new java.awt.Color(51, 51, 51));
        Espacio2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Espacio2.setForeground(new java.awt.Color(255, 255, 255));
        Espacio2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Espacio2.setText("2");
        Espacio2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Espacio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 30, 30));

        Espacio1.setEditable(false);
        Espacio1.setBackground(new java.awt.Color(51, 51, 51));
        Espacio1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Espacio1.setForeground(new java.awt.Color(255, 255, 255));
        Espacio1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Espacio1.setText("1");
        Espacio1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Espacio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 30, 30));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("X");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 40, 40));

        Cuerdas.setBackground(new java.awt.Color(51, 51, 51));
        Cuerdas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Puente3.setEditable(false);
        Puente3.setBackground(new java.awt.Color(255, 255, 255));
        Puente3.setColumns(20);
        Puente3.setRows(5);
        Puente3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cuerdas.add(Puente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 20, 100));

        Puente2.setEditable(false);
        Puente2.setBackground(new java.awt.Color(255, 255, 255));
        Puente2.setColumns(20);
        Puente2.setRows(5);
        Puente2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cuerdas.add(Puente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 20, 150));

        Puente1.setEditable(false);
        Puente1.setBackground(new java.awt.Color(255, 255, 255));
        Puente1.setColumns(20);
        Puente1.setRows(5);
        Puente1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cuerdas.add(Puente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 20, 185));

        Clavijero.setEditable(false);
        Clavijero.setBackground(new java.awt.Color(255, 255, 255));
        Clavijero.setColumns(20);
        Clavijero.setRows(5);
        Clavijero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cuerdas.add(Clavijero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 200));

        Dedos1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Dedos1.setForeground(new java.awt.Color(255, 255, 255));
        Dedos1.setText("O");
        Cuerdas.add(Dedos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Dedos2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Dedos2.setForeground(new java.awt.Color(255, 255, 255));
        Dedos2.setText("O");
        Cuerdas.add(Dedos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        Dedos3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Dedos3.setForeground(new java.awt.Color(255, 255, 255));
        Dedos3.setText("O");
        Cuerdas.add(Dedos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        Dedos4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Dedos4.setForeground(new java.awt.Color(255, 255, 255));
        Dedos4.setText("O");
        Cuerdas.add(Dedos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        Dedos5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Dedos5.setForeground(new java.awt.Color(255, 255, 255));
        Dedos5.setText("O");
        Cuerdas.add(Dedos5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        Dedos6.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Dedos6.setForeground(new java.awt.Color(255, 255, 255));
        Dedos6.setText("O");
        Cuerdas.add(Dedos6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        Dedos7.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Dedos7.setForeground(new java.awt.Color(255, 255, 255));
        Dedos7.setText("O");
        Cuerdas.add(Dedos7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        Dedos8.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Dedos8.setForeground(new java.awt.Color(255, 255, 255));
        Dedos8.setText("O");
        Cuerdas.add(Dedos8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        Dedos9.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Dedos9.setForeground(new java.awt.Color(255, 255, 255));
        Dedos9.setText("O");
        Cuerdas.add(Dedos9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        Dedos10.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Dedos10.setForeground(new java.awt.Color(255, 255, 255));
        Dedos10.setText("O");
        Cuerdas.add(Dedos10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        Dedos11.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Dedos11.setForeground(new java.awt.Color(255, 255, 255));
        Dedos11.setText("O");
        Cuerdas.add(Dedos11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        Dedos12.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Dedos12.setForeground(new java.awt.Color(255, 255, 255));
        Dedos12.setText("O");
        Cuerdas.add(Dedos12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        Dedos13.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Dedos13.setForeground(new java.awt.Color(255, 255, 255));
        Dedos13.setText("O");
        Cuerdas.add(Dedos13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        Dedos14.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Dedos14.setForeground(new java.awt.Color(255, 255, 255));
        Dedos14.setText("O");
        Cuerdas.add(Dedos14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        Dedos15.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Dedos15.setForeground(new java.awt.Color(255, 255, 255));
        Dedos15.setText("O");
        Cuerdas.add(Dedos15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        Dedos16.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Dedos16.setForeground(new java.awt.Color(255, 255, 255));
        Dedos16.setText("O");
        Cuerdas.add(Dedos16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        Dedos17.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Dedos17.setForeground(new java.awt.Color(255, 255, 255));
        Dedos17.setText("O");
        Cuerdas.add(Dedos17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        Dedos18.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Dedos18.setForeground(new java.awt.Color(255, 255, 255));
        Dedos18.setText("O");
        Cuerdas.add(Dedos18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        Dedos19.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Dedos19.setForeground(new java.awt.Color(255, 255, 255));
        Dedos19.setText("O");
        Cuerdas.add(Dedos19, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        Dedos20.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Dedos20.setForeground(new java.awt.Color(255, 255, 255));
        Dedos20.setText("O");
        Cuerdas.add(Dedos20, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        Dedos21.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Dedos21.setForeground(new java.awt.Color(255, 255, 255));
        Dedos21.setText("O");
        Cuerdas.add(Dedos21, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        Dedos22.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Dedos22.setForeground(new java.awt.Color(255, 255, 255));
        Dedos22.setText("O");
        Cuerdas.add(Dedos22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        Dedos23.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Dedos23.setForeground(new java.awt.Color(255, 255, 255));
        Dedos23.setText("O");
        Cuerdas.add(Dedos23, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        Dedos24.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Dedos24.setForeground(new java.awt.Color(255, 255, 255));
        Dedos24.setText("O");
        Cuerdas.add(Dedos24, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        Traste1.setEditable(false);
        Traste1.setBackground(new java.awt.Color(153, 153, 153));
        Traste1.setColumns(20);
        Traste1.setRows(5);
        Cuerdas.add(Traste1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 5, 200));

        Traste2.setEditable(false);
        Traste2.setBackground(new java.awt.Color(153, 153, 153));
        Traste2.setColumns(20);
        Traste2.setRows(5);
        Cuerdas.add(Traste2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 5, 200));

        Traste3.setEditable(false);
        Traste3.setBackground(new java.awt.Color(153, 153, 153));
        Traste3.setColumns(20);
        Traste3.setRows(5);
        Cuerdas.add(Traste3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 5, 200));

        Cuerda1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        Cuerda1.setForeground(new java.awt.Color(204, 204, 204));
        Cuerda1.setText("_______________");
        Cuerdas.add(Cuerda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, -1));

        Cuerda2.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        Cuerda2.setForeground(new java.awt.Color(204, 204, 204));
        Cuerda2.setText("_______________");
        Cuerdas.add(Cuerda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        Cuerda3.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        Cuerda3.setForeground(new java.awt.Color(204, 204, 204));
        Cuerda3.setText("_______________");
        Cuerdas.add(Cuerda3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        Cuerda4.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        Cuerda4.setForeground(new java.awt.Color(204, 204, 204));
        Cuerda4.setText("_______________");
        Cuerdas.add(Cuerda4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        Cuerda5.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        Cuerda5.setForeground(new java.awt.Color(204, 204, 204));
        Cuerda5.setText("_______________");
        Cuerda5.setToolTipText("");
        Cuerdas.add(Cuerda5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        Cuerda6.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        Cuerda6.setForeground(new java.awt.Color(204, 204, 204));
        Cuerda6.setText("_______________");
        Cuerdas.add(Cuerda6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        getContentPane().add(Cuerdas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 400, 200));

        LabelWallpaper.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(LabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int Acorde = CmbAcorde.getSelectedIndex();
        int Familia = CmbFamilia.getSelectedIndex();
        Limpiar();
        Encontrar(Acorde, Familia);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcordesGuitarra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcordesGuitarra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcordesGuitarra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcordesGuitarra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcordesGuitarra().setVisible(true);
            }
        });
    }

    public void Encontrar(int Acorde, int Familia) {

        int traste1 = 0;

        if (Familia == 0) {
            traste1 = Mayor(Acorde);
        } else if (Familia == 1) {
            traste1 = Menor(Acorde);
        }

        if (traste1 == 1) {
            Clavijero.setVisible(true);
        } else {
            Clavijero.setVisible(false);
        }
        Espacio1.setText("" + traste1 + "");
        Espacio2.setText("" + (traste1 + 1) + "");
        Espacio3.setText("" + (traste1 + 2) + "");
        Espacio4.setText("" + (traste1 + 3) + "");
    }

    public int Mayor(int Acorde) {
        int traste1 = 0;

        if (Acorde == 0) {
            traste1 = 1;
            Dedos2.setVisible(true);
            Dedos10.setVisible(true);
            Dedos17.setVisible(true);
            Cuerda6.setForeground(Color.red);
            LabelAcordeName.setText(" DO Mayor");
            LabelAcorde.setText("C");
        } else if (Acorde == 1) {
            traste1 = 1;
            Puente3.setVisible(true);
            Dedos8.setVisible(true);
            Dedos16.setVisible(true);
            Dedos23.setVisible(true);
            Cuerda6.setForeground(Color.red);
            LabelAcordeName.setText(" DO Sostenido Mayor");
            LabelAcorde.setText("C#");
        } else if (Acorde == 2) {
            traste1 = 1;
            Dedos7.setVisible(true);
            Dedos9.setVisible(true);
            Dedos14.setVisible(true);
            Cuerda5.setForeground(Color.red);
            Cuerda6.setForeground(Color.red);
            LabelAcordeName.setText(" RE Mayor");
            LabelAcorde.setText("D");
        } else if (Acorde == 3) {
            traste1 = 1;
            Dedos4.setVisible(true);
            Dedos13.setVisible(true);
            Dedos15.setVisible(true);
            Dedos20.setVisible(true);
            Cuerda5.setForeground(Color.red);
            Cuerda6.setForeground(Color.red);
            LabelAcordeName.setText(" RE Sostenido Mayor");
            LabelAcorde.setText("D#");
        } else if (Acorde == 4) {
            traste1 = 1;
            Dedos3.setVisible(true);
            Dedos10.setVisible(true);
            Dedos11.setVisible(true);
            LabelAcordeName.setText("MI Mayor");
            LabelAcorde.setText("E");
        } else if (Acorde == 5) {
            traste1 = 1;
            Puente1.setVisible(true);
            Dedos9.setVisible(true);
            Dedos16.setVisible(true);
            Dedos17.setVisible(true);
            LabelAcordeName.setText("FA Mayor");
            LabelAcorde.setText("F");
        } else if (Acorde == 6) {
            traste1 = 2;
            Puente1.setVisible(true);
            Dedos9.setVisible(true);
            Dedos16.setVisible(true);
            Dedos17.setVisible(true);
            LabelAcordeName.setText("FA Sostenido Mayor");
            LabelAcorde.setText("F#");
        } else if (Acorde == 7) {
            traste1 = 1;
            Dedos11.setVisible(true);
            Dedos18.setVisible(true);
            Dedos13.setVisible(true);
            Dedos14.setVisible(true);
            LabelAcordeName.setText("SOL Mayor");
            LabelAcorde.setText("G");
        } else if (Acorde == 8) {
            traste1 = 4;
            Puente1.setVisible(true);
            Dedos9.setVisible(true);
            Dedos16.setVisible(true);
            Dedos17.setVisible(true);
            LabelAcordeName.setText("SOL Sostenido Mayor");
            LabelAcorde.setText("G#");
        } else if (Acorde == 9) {
            traste1 = 1;
            Dedos8.setVisible(true);
            Dedos9.setVisible(true);
            Dedos10.setVisible(true);
            Cuerda6.setForeground(Color.red);
            LabelAcordeName.setText(" LA Mayor");
            LabelAcorde.setText("A");
        } else if (Acorde == 10) {
            traste1 = 1;
            Puente2.setVisible(true);
            Dedos14.setVisible(true);
            Dedos15.setVisible(true);
            Dedos16.setVisible(true);
            Cuerda6.setForeground(Color.red);
            LabelAcordeName.setText(" LA Sostenido Mayor");
            LabelAcorde.setText("A#");
        } else if (Acorde == 11) {
            traste1 = 2;
            Puente2.setVisible(true);
            Dedos14.setVisible(true);
            Dedos15.setVisible(true);
            Dedos16.setVisible(true);
            Cuerda6.setForeground(Color.red);
            LabelAcordeName.setText(" SI Mayor");
            LabelAcorde.setText("B");
        }

        return traste1;
    }

    
    public int Menor(int Acorde) {
        int traste1 = 0;
        if (Acorde == 0) {
            traste1 = 3;
            Puente2.setVisible(true);
            Dedos8.setVisible(true);
            Dedos15.setVisible(true);
            Dedos16.setVisible(true);
            Cuerda6.setForeground(Color.red);
            LabelAcordeName.setText(" DO Menor");
            LabelAcorde.setText("Cm");
        } else if (Acorde == 1) {
            traste1 = 4;
            Puente2.setVisible(true);
            Dedos8.setVisible(true);
            Dedos15.setVisible(true);
            Dedos16.setVisible(true);
            Cuerda6.setForeground(Color.red);
            LabelAcordeName.setText(" DO Sostenido Menor");
            LabelAcorde.setText("C#m");
        } else if (Acorde == 2) {
            traste1 = 1;
            Dedos1.setVisible(true);
            Dedos9.setVisible(true);
            Dedos14.setVisible(true);
            Cuerda5.setForeground(Color.red);
            Cuerda6.setForeground(Color.red);
            LabelAcordeName.setText(" RE Menor");
            LabelAcorde.setText("Dm");
        } else if (Acorde == 3) {
            traste1 = 1;
            Dedos4.setVisible(true);
            Dedos7.setVisible(true);
            Dedos15.setVisible(true);
            Dedos20.setVisible(true);
            Cuerda5.setForeground(Color.red);
            Cuerda6.setForeground(Color.red);
            LabelAcordeName.setText(" RE Sostenido Menor");
            LabelAcorde.setText("D#m");
        } else if (Acorde == 4) {
            traste1 = 1;
            Dedos10.setVisible(true);
            Dedos11.setVisible(true);
            LabelAcordeName.setText("MI Menor");
            LabelAcorde.setText("Em");
        } else if (Acorde == 5) {
            traste1 = 1;
            Puente1.setVisible(true);
            Dedos16.setVisible(true);
            Dedos17.setVisible(true);
            LabelAcordeName.setText("FA Menor");
            LabelAcorde.setText("Fm");
        } else if (Acorde == 6) {
            traste1 = 2;
            Puente1.setVisible(true);
            Dedos16.setVisible(true);
            Dedos17.setVisible(true);
            LabelAcordeName.setText("FA Sostenido Menor");
            LabelAcorde.setText("F#m");
        } else if (Acorde == 7) {
            traste1 = 3;
            Puente1.setVisible(true);
            Dedos16.setVisible(true);
            Dedos17.setVisible(true);
            LabelAcordeName.setText("SOL Menor");
            LabelAcorde.setText("Gm");
        } else if (Acorde == 8) {
            traste1 = 4;
            Puente1.setVisible(true);
            Dedos16.setVisible(true);
            Dedos17.setVisible(true);
            LabelAcordeName.setText("SOL Sostenido Menor");
            LabelAcorde.setText("G#m");
        } else if (Acorde == 9) {
            traste1 = 1;
            Dedos2.setVisible(true);
            Dedos9.setVisible(true);
            Dedos10.setVisible(true);
            Cuerda6.setForeground(Color.red);
            LabelAcordeName.setText(" LA Menor");
            LabelAcorde.setText("Am");
        } else if (Acorde == 10) {
            traste1 = 1;
            Puente2.setVisible(true);
            Dedos8.setVisible(true);
            Dedos15.setVisible(true);
            Dedos16.setVisible(true);
            Cuerda6.setForeground(Color.red);
            LabelAcordeName.setText(" LA Sostenido Menor");
            LabelAcorde.setText("A#m");
        } else if (Acorde == 11) {
            traste1 = 2;
            Puente2.setVisible(true);
            Dedos8.setVisible(true);
            Dedos15.setVisible(true);
            Dedos16.setVisible(true);
            Cuerda6.setForeground(Color.red);
            LabelAcordeName.setText(" SI Menor");
            LabelAcorde.setText("Bm");
        }

        return traste1;
    }

    public void Limpiar() {
        Cuerda1.setForeground(new Color(204, 204, 204));
        Cuerda2.setForeground(new Color(204, 204, 204));
        Cuerda3.setForeground(new Color(204, 204, 204));
        Cuerda4.setForeground(new Color(204, 204, 204));
        Cuerda5.setForeground(new Color(204, 204, 204));
        Cuerda6.setForeground(new Color(204, 204, 204));
        Puente1.setVisible(false);
        Puente2.setVisible(false);
        Puente3.setVisible(false);
        Dedos1.setVisible(false);
        Dedos2.setVisible(false);
        Dedos3.setVisible(false);
        Dedos4.setVisible(false);
        Dedos5.setVisible(false);
        Dedos6.setVisible(false);
        Dedos7.setVisible(false);
        Dedos8.setVisible(false);
        Dedos9.setVisible(false);
        Dedos10.setVisible(false);
        Dedos11.setVisible(false);
        Dedos12.setVisible(false);
        Dedos13.setVisible(false);
        Dedos14.setVisible(false);
        Dedos15.setVisible(false);
        Dedos16.setVisible(false);
        Dedos17.setVisible(false);
        Dedos18.setVisible(false);
        Dedos19.setVisible(false);
        Dedos20.setVisible(false);
        Dedos21.setVisible(false);
        Dedos22.setVisible(false);
        Dedos23.setVisible(false);
        Dedos24.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Clavijero;
    private javax.swing.JComboBox<String> CmbAcorde;
    private javax.swing.JComboBox<String> CmbFamilia;
    private javax.swing.JLabel Cuerda1;
    private javax.swing.JLabel Cuerda2;
    private javax.swing.JLabel Cuerda3;
    private javax.swing.JLabel Cuerda4;
    private javax.swing.JLabel Cuerda5;
    private javax.swing.JLabel Cuerda6;
    private javax.swing.JPanel Cuerdas;
    private javax.swing.JLabel Dedos1;
    private javax.swing.JLabel Dedos10;
    private javax.swing.JLabel Dedos11;
    private javax.swing.JLabel Dedos12;
    private javax.swing.JLabel Dedos13;
    private javax.swing.JLabel Dedos14;
    private javax.swing.JLabel Dedos15;
    private javax.swing.JLabel Dedos16;
    private javax.swing.JLabel Dedos17;
    private javax.swing.JLabel Dedos18;
    private javax.swing.JLabel Dedos19;
    private javax.swing.JLabel Dedos2;
    private javax.swing.JLabel Dedos20;
    private javax.swing.JLabel Dedos21;
    private javax.swing.JLabel Dedos22;
    private javax.swing.JLabel Dedos23;
    private javax.swing.JLabel Dedos24;
    private javax.swing.JLabel Dedos3;
    private javax.swing.JLabel Dedos4;
    private javax.swing.JLabel Dedos5;
    private javax.swing.JLabel Dedos6;
    private javax.swing.JLabel Dedos7;
    private javax.swing.JLabel Dedos8;
    private javax.swing.JLabel Dedos9;
    private javax.swing.JTextField Espacio1;
    private javax.swing.JTextField Espacio2;
    private javax.swing.JTextField Espacio3;
    private javax.swing.JTextField Espacio4;
    private javax.swing.JLabel LabelAcorde;
    private javax.swing.JLabel LabelAcordeName;
    private javax.swing.JLabel LabelWallpaper;
    private javax.swing.JTextField NCuerda1;
    private javax.swing.JTextField NCuerda2;
    private javax.swing.JTextField NCuerda3;
    private javax.swing.JTextField NCuerda4;
    private javax.swing.JTextField NCuerda5;
    private javax.swing.JTextField NCuerda6;
    private javax.swing.JTextField NTraste;
    private javax.swing.JTextArea Puente1;
    private javax.swing.JTextArea Puente2;
    private javax.swing.JTextArea Puente3;
    private javax.swing.JTextArea Traste1;
    private javax.swing.JTextArea Traste2;
    private javax.swing.JTextArea Traste3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
