/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author MINEDUCYT
 */
public class Info extends javax.swing.JFrame {

    /**
     * Creates new form ArmadorEscalas
     */
    public Info() {
        initComponents();

        setTitle(" Informacion de la Aplicación");
        this.setLocationRelativeTo(null);

        ImageIcon wallpaper = new ImageIcon("src/img/wallpaperPiano.jpg");
        Icon icon = new ImageIcon(wallpaper.getImage().getScaledInstance(LabelWallpaper.getWidth(),
                LabelWallpaper.getHeight(), Image.SCALE_DEFAULT));
        LabelWallpaper.setIcon(icon);

        jTextArea1.setCaretPosition(0);

        ImageIcon Facebook = new ImageIcon("src/img/facebook.png");
        Icon iconf = new ImageIcon(Facebook.getImage().getScaledInstance(BtnFacebook.getWidth(),
                BtnFacebook.getHeight(), Image.SCALE_DEFAULT));
        BtnFacebook.setIcon(iconf);

        ImageIcon Instagram = new ImageIcon("src/img/instagram.png");
        Icon iconi = new ImageIcon(Instagram.getImage().getScaledInstance(BtnInstagram.getWidth(),
                BtnInstagram.getHeight(), Image.SCALE_DEFAULT));
        BtnInstagram.setIcon(iconi);
        BtnInstagram.setIcon(iconi);

        ImageIcon Github = new ImageIcon("src/img/github.png");
        Icon icong = new ImageIcon(Github.getImage().getScaledInstance(BtnGithub.getWidth(),
                BtnGithub.getHeight(), Image.SCALE_DEFAULT));
        BtnGithub.setIcon(icong);

    }

    @Override
    public Image getIconImage() {
        URL resourceUrl = ClassLoader.getSystemResource("img/icono.png");
        if (resourceUrl != null) {
            Image retValue = Toolkit.getDefaultToolkit().getImage(resourceUrl);
            return retValue;
        } else {
            System.err.println("No se pudo encontrar el recurso 'icono.png'");
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnFacebook = new javax.swing.JButton();
        BtnGithub = new javax.swing.JButton();
        BtnInstagram = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        LabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnFacebook.setBackground(new java.awt.Color(51, 51, 51));
        BtnFacebook.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnFacebook.setForeground(new java.awt.Color(255, 255, 255));
        BtnFacebook.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnFacebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFacebookActionPerformed(evt);
            }
        });
        getContentPane().add(BtnFacebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 60, 60));

        BtnGithub.setBackground(new java.awt.Color(51, 51, 51));
        BtnGithub.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnGithub.setForeground(new java.awt.Color(255, 255, 255));
        BtnGithub.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnGithub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGithubActionPerformed(evt);
            }
        });
        getContentPane().add(BtnGithub, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 60, 60));

        BtnInstagram.setBackground(new java.awt.Color(51, 51, 51));
        BtnInstagram.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnInstagram.setForeground(new java.awt.Color(255, 255, 255));
        BtnInstagram.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnInstagram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInstagramActionPerformed(evt);
            }
        });
        getContentPane().add(BtnInstagram, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 130, 60, 60));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(51, 51, 51));
        jTextField5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("Redes Sociales");
        jTextField5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 230, 30));

        jScrollPane1.setBorder(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("MusicNotes v2.0\n\n- Adicion de 1 tema nuevo en \"Teoria Musical\" -> \"Escalas Modales\"\n- Reorganizaion de botones\n- \"Acordes Piano\" movido a Inicio\n- \"Acordes Guitarra\" movido a Inicio\n- \"Generador de Escalas\" movido a Extra\n- Botones de redes sociales movido a Info\n- Eliminacion de la pestaña \"Redes Sociales\"\n\n----------------------------------------------------------------\nMusicNotes v1.0\n\n-Cambio en el diseño de todas las pestañas\n-Adicion de 39 Temas a la pestaña \"Teoria Muscal\"\n-Modificacion de Nombre de \"Acordes\" a \"Acordes de Piano\"\n-Adicion de la Pestaña \"Acordes de guitarra\"\n-Adicion de 2 familias de acordes a \"Acordes de Guitarra\"\n-Adicion de la tabla \"Acordes\" en la pestaña \"Galeria de Escalas\"\n\n----------------------------------------------------------------\nMusicNotes Beta v1.5\n\n-Actualización del software para formar los acordes\n-Modificación de la pestaña \"Extra\" para añadir sus funciones\n-Adición de pestaña \"Redes Sociales\"\n-Adición de Pestaña \"Teoría Musical\"\n-Adicion de Pestaña \"Informacion de la Aplicación\"\n-Modificación de estilo en las Tablas de \"Galería de Escalas\" y \"Generador de Escalas\"\n-Adicion de 20 Familias a \"Galeria de Acordes\"\n-Adicion de la pestaña \"Teoria Musical\"\n-Adicion de 9 Temas a la pestaña \"Teoria Musical\"\n----------------------------------------------------------------\nMusicNotes Beta v1.0\n\n-Adición de la pestaña \"Generador de Escalas\"\n-Modificación del estilo en todo el programa\n-Adición de fondos en todas las pestañas\n-Apertura del programa a todo el público\n-Adicion de 6 escalas PreCargadas en la pestaña \"Generador de Escalas\"\n----------------------------------------------------------------\nMusicNotes Alfa v0.1\n\n-Adición de la pestaña \"Galería de Acordes\"\n-Adición de la pestaña \"Galería de Escalas\"\n-Adición de 15 familias de acordes en la pestaña \"Galería de Acordes\"\n-Adición de las 24 escalas (12 mayores, 12 menores) en la pestaña \"Galería de Escalas\"\n\n----------------------------------------------------------------\nMusicNotes Pre Alfa v0.0.1\n\n- Creacion del Software para genera escalas\n- Adicion de las 12 notas disponibles\n- Adicion de la escala Mayor al generador de escalas de consola");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 540, 240));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("MusicNotes v2.0");
        jTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 520, 70));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(51, 51, 51));
        jTextField2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Notas de la version");
        jTextField2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 170, 40));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(51, 51, 51));
        jTextField4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("Hecho con Java17");
        jTextField4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 230, 30));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(51, 51, 51));
        jTextField3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("Creado Por Bryan Guevara");
        jTextField3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 230, 30));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("X");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 40, 40));

        LabelWallpaper.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(LabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void BtnFacebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFacebookActionPerformed
        if (java.awt.Desktop.isDesktopSupported()) {
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
            if (desktop.isSupported(java.awt.Desktop.Action.BROWSE)) {
                try {
                    java.net.URI instagram = new java.net.URI("https://www.facebook.com/profile.php?id=61556965297606");
                    desktop.browse(instagram);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_BtnFacebookActionPerformed

    private void BtnGithubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGithubActionPerformed
        if (java.awt.Desktop.isDesktopSupported()) {
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
            if (desktop.isSupported(java.awt.Desktop.Action.BROWSE)) {
                try {
                    java.net.URI instagram = new java.net.URI("https://github.com/BryanGuevara");
                    desktop.browse(instagram);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_BtnGithubActionPerformed

    private void BtnInstagramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInstagramActionPerformed
        if (java.awt.Desktop.isDesktopSupported()) {
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
            if (desktop.isSupported(java.awt.Desktop.Action.BROWSE)) {
                try {
                    java.net.URI instagram = new java.net.URI("https://www.instagram.com/bryanguevaradev/");
                    desktop.browse(instagram);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_BtnInstagramActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnFacebook;
    private javax.swing.JButton BtnGithub;
    private javax.swing.JButton BtnInstagram;
    private javax.swing.JLabel LabelWallpaper;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
